#!/usr/bin/env python3
"""Build assets/fonts/term.ttf (JetBrains Mono subset for the terminal) and
components/deck_term/term_glyphs.h, the list of codepoints it contains, so
the renderer can substitute '?' instead of asking the font for missing
glyphs (tiny_ttf logs an error for every miss).

Usage: tools/subset_term_font.py path/to/JetBrainsMono[wght].ttf
Needs fonttools.
"""
import pathlib
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

RANGES = [
    (0x20, 0x7E), (0xA0, 0xFF),        # ASCII, Latin-1
    (0x2010, 0x2027), (0x2030, 0x205E),  # punctuation
    (0x2190, 0x21FF),                  # arrows
    (0x2200, 0x22FF), (0x2300, 0x23FF),  # math, technical
    (0x2500, 0x259F),                  # box drawing, blocks
    (0x25A0, 0x25FF),                  # geometric shapes
    (0xE0A0, 0xE0B3),                  # powerline
]

root = pathlib.Path(__file__).resolve().parent.parent
src = sys.argv[1]
cmap = TTFont(src).getBestCmap()
wanted = [cp for a, b in RANGES for cp in range(a, b + 1) if cp in cmap]

opts = subset.Options()
opts.hinting = False
opts.layout_features = []
font = TTFont(src)
sub = subset.Subsetter(options=opts)
sub.populate(unicodes=wanted)
sub.subset(font)
out = root / "assets/fonts/term.ttf"
font.save(out)

# Collapse into ranges for a small lookup table.
ranges, start, prev = [], None, None
for cp in wanted:
    if start is None:
        start = prev = cp
    elif cp == prev + 1:
        prev = cp
    else:
        ranges.append((start, prev))
        start = prev = cp
ranges.append((start, prev))

hdr = root / "components/deck_term/term_glyphs.h"
with hdr.open("w") as f:
    f.write("/* Generated by tools/subset_term_font.py. Do not edit. */\n#pragma once\n\n#include <stdint.h>\n\n")
    f.write("static const uint32_t g_term_glyph_ranges[][2] = {\n")
    for a, b in ranges:
        f.write(f"    {{0x{a:04X}, 0x{b:04X}}},\n")
    f.write("};\n\n#define TERM_GLYPH_RANGE_COUNT (sizeof(g_term_glyph_ranges) / sizeof(g_term_glyph_ranges[0]))\n")
print(f"wrote {out.name} ({out.stat().st_size} bytes, {len(wanted)} glyphs, {len(ranges)} ranges)")
